### ISSUE TITLE
Phone Unlocked Behavior doesn't appear to be working under iOS9

### ISSUE THREAD

**Issue by ketsugi** [tyhoff/PebbleProfiles#5]
Updated to iOS9 today with the new Pangu jailbreak and reinstalled the Pebble Profiles tweak. I have the "Phone Unlocked Behavior" setting enabled but am still receiving notifications on my Pebble when the phone is unlocked.

**Comment by joemerlino** [comment]
Aware of this issue, I'll update my iPhone this weekend and try to update Pebble Profiles ASAP.

**Comment by ketsugi** [comment]
Cool, thanks. No hurry, really, just wanted to drop you an FYI and couldn't find any other way to reach you (besides emailing you directly which I thought might be a little inappropriate).

**Comment by joemerlino** [comment]
Yup! Thanks :)
